vim.cmd.set('nu')

vim.cmd.set('tabstop=2')
vim.cmd.set('shiftwidth=2')
vim.cmd.set('noexpandtab')
vim.cmd.set('noswf')
vim.cmd.set('pumblend=20')
vim.cmd.set('winblend=20')
vim.cmd.set('scrolloff=5')
vim.cmd.set('numberwidth=1')
vim.cmd.set('termguicolors')
vim.cmd.set('cursorline')
