theme="dracula_transparent"

[editor]
auto-save=true
true-color=true
auto-format=false
bufferline="multiple"
idle-timeout=0
completion-trigger-len=1
line-number = "relative"

[editor.lsp]
display-messages=true
display-inlay-hints=false

[editor.file-picker]
hidden=false

[editor.indent-guides]
render=true
skip-levels=1
# character="╎"

[editor.gutters]
line-numbers = {min-width = 1}

[keys.normal.g]
l = "extend_to_line_end"
h = "extend_to_line_start"
s = "extend_to_first_nonwhitespace"

[keys.normal.space]
x = ":bc"
